services:
  postgres_insecure:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on", "-c", "log_disconnections=on", "-c", "log_duration=on"]
    ports:
      - 6450:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 1s
      interval: 5s

  postgres_secure:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on", "-c", "log_disconnections=on", "-c", "log_duration=on"]
    ports:
      - 6451:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 1s
      interval: 5s

  postgres_ssl:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - ./certs:/certs
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on", "-c", "log_disconnections=on", "-c", "log_duration=on", "-c", "ssl=on", "-c", "ssl_cert_file=/certs/server.crt", "-c", "ssl_key_file=/certs/server.key"]
    ports:
      - 6452:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 1s
      interval: 5s
    depends_on:
      openssl:
        condition: service_completed_successfully

  openssl:
    image: alpine:3.14
    command: >
      sh -c "apk add --no-cache openssl &&
        openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -subj '/CN=localhost' -keyout /certs/server.key -out /certs/server.crt"
    volumes:
      - ./certs:/certs

  test:
    image: swift:6.0.3
    volumes:
      - .:/app
    working_dir: /app
    command: ["swift", "test"]
    depends_on:
      postgres_insecure:
        condition: service_healthy
      postgres_secure:
        condition: service_healthy
      postgres_ssl:
        condition: service_healthy
